global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  # The auth token for Hipchat.
  hipchat_auth_token: '1234556789'
  # Alternative host for Hipchat.
  hipchat_api_url: 'https://hipchat.foobar.org/'
  slack_api_url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX

# The directory from which notification templates are read.
templates: 
- '/vagrant/provision/prometheus/alertmanager.tmpl'

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname', 'instance', 'service']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 3h 

  # A default receiver
  receiver: team-X

  # All the above attributes are inherited by all child routes and can 
  # overwritten on each.

  # The child route trees.
  routes:
  # This routes performs a regular expression match on alert labels to
  # catch alerts that are related to a list of services.
  - match:
      type: infra
    continue: true
    routes:
      - match:
          severity: danger
        receiver: team-I-danger
      - match:
          severity: warn
        receiver: team-I-warn
  - match:
      type: app
    continue: true
    routes:
      - match:
          service: A
        routes:
          - match:
              severiry: danger
            receiver: team-A-danger
          - match:
              severity: warn
            receiver: team-A-warn
      - match:
          service: B
        routes:
          - match:
              severiry: danger
            receiver: team-B-danger
          - match:
              severity: warn
            receiver: team-B-warn
  - match:
      type: infra
      service: B
    continue: true
    routes:
      - match:
          severity: danger
        receiver: team-B-danger
      - match:
          severity: warn
        receiver: team-B-warn

############################################

receivers:
- name: 'team-A-warn'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-a-warn
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'
    color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'

- name: 'team-A-danger'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-a-danger
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'
  
- name: 'team-B-warn'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-b-warn
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'
    color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'

- name: 'team-B-danger'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-b-danger
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'
  
- name: 'team-I-warn'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-i-warn
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'
    color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'

- name: 'team-I-danger'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-i-danger
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'

# 条件判定に該当しないものを流す先    
- name: 'team-X'
  slack_configs:
  - channel: test-webhook
    send_resolved: true
    username: prometheus-x
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'
    title_link: '{{ template "custom_slack_titlelink" . }}'
