global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - /vagrant/provision/prometheus/rule.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090

  - job_name: 'nodes'
    static_configs:
      - targets: 
          - 192.168.33.101:9100
          - 192.168.33.102:9100
        labels:
          service: A
      - targets:
          - 192.168.33.111:9100
          - 192.168.33.112:9100
        labels:
          service: B

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - http://192.168.33.101    # nodeA1
          - http://192.168.33.102    # nodeA2
        labels:
          service: A
      - targets:
          - http://192.168.33.111    # nodeB1
          - http://192.168.33.112    # nodeB2
        labels:
          service: B        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

