groups:
- name: node_metrics
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    labels:
      severity: danger
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

- name: http_healthcheck
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: HttpHealthCheckUnhealthy
    expr: probe_success == 0
    for: 2m
    labels:
      severity: warn
    annotations:
      summary: "Target {{ $labels.instance }} is unhealthy."
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."
